In [3]:
import pandas as pd 
import numpy as np

In [27]:
rows, cols = 10,5

data = np.random.randn(rows,cols)


df= pd.DataFrame(data,columns=[f'col_{i}' for i in range(cols)])

# Randamly assign Nan values
nan_vals = np.random.choice(df.size,size=int(df.size*0.2),replace=False)

df.values.ravel()[nan_vals] = np.nan

# nan_vals
df

      col_0     col_1     col_2     col_3     col_4
0 -1.342045       NaN -0.709832       NaN  1.510812
1 -0.619233 -0.951379  1.377936  1.397578       NaN
2  2.735269 -0.462304 -0.450791 -0.320104 -0.759665
3 -0.221267 -0.941401 -0.888113 -0.098734  0.510390
4  0.643467       NaN  1.508401 -1.368138       NaN
5       NaN       NaN  0.390260  0.383689  0.405514
6  0.600640  0.807487 -0.975705  0.780432       NaN
7  1.338374       NaN  0.159811 -0.446436 -0.006476
8  1.774805  0.583547       NaN  0.319385 -0.215985
9  0.234275  0.957033  0.018040 -0.355998 -0.146622

In [7]:
df['col_0'].isna()
# df.notna()

0    False
1     True
2    False
3    False
4    False
5    False
6    False
7    False
8    False
9    False
Name: col_0, dtype: bool

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   col_0   9 non-null      float64
 1   col_1   7 non-null      float64
 2   col_2   9 non-null      float64
 3   col_3   6 non-null      float64
 4   col_4   9 non-null      float64
dtypes: float64(5)
memory usage: 532.0 bytes

In [14]:
df.dtypes.value_counts()

float64    5
Name: count, dtype: int64

In [8]:
df.dtypes

col_0    float64
col_1    float64
col_2    float64
col_3    float64
col_4    float64
dtype: object

In [17]:
df_num = pd.Series([1,5,np.nan,9,7,2.0])
df_num[0] = None # or df_num[0] = np.nan
df_num

0    NaN
1    5.0
2    NaN
3    9.0
4    7.0
5    2.0
dtype: float64

In [18]:
df_dt = pd.Series(['2024-01-01', None, '2024-01-03',np.nan])

df_dt = pd.to_datetime(df_dt)

df_dt

0   2024-01-01
1          NaT
2   2024-01-03
3          NaT
dtype: datetime64[ns]

In [19]:
df_ob = pd.Series(['a', None, 'z',np.nan])

df_ob

0       a
1    None
2       z
3     NaN
dtype: object

In [9]:
df
# df.fillna(0)
# df.fillna('NA')

      col_0     col_1     col_2     col_3     col_4
0       NaN -0.488876 -0.909393       NaN  0.108884
1  0.241300  0.464170       NaN -0.033699 -1.513093
2 -0.518444  0.097376  0.654823       NaN  0.084360
3 -1.091641       NaN  0.883421       NaN  0.822185
4       NaN -0.883538 -1.198184  1.269706       NaN
5  0.911469  1.269089       NaN  1.486603       NaN
6       NaN  0.685717 -1.255854       NaN -0.641495
7  1.113200 -0.115718 -0.172060       NaN       NaN
8  0.242572 -0.726256       NaN       NaN -1.283813
9       NaN       NaN  0.219863       NaN       NaN

In [14]:
df.ffill()
# df.fillna(method='ffill')

      col_0     col_1     col_2     col_3     col_4
0       NaN -0.488876 -0.909393       NaN  0.108884
1  0.241300  0.464170 -0.909393 -0.033699 -1.513093
2 -0.518444  0.097376  0.654823 -0.033699  0.084360
3 -1.091641  0.097376  0.883421 -0.033699  0.822185
4 -1.091641 -0.883538 -1.198184  1.269706  0.822185
5  0.911469  1.269089 -1.198184  1.486603  0.822185
6  0.911469  0.685717 -1.255854  1.486603 -0.641495
7  1.113200 -0.115718 -0.172060  1.486603 -0.641495
8  0.242572 -0.726256 -0.172060  1.486603 -1.283813
9  0.242572 -0.726256  0.219863  1.486603 -1.283813

In [17]:
df.bfill()

      col_0     col_1     col_2     col_3     col_4
0  0.241300 -0.488876 -0.909393 -0.033699  0.108884
1  0.241300  0.464170  0.654823 -0.033699 -1.513093
2 -0.518444  0.097376  0.654823  1.269706  0.084360
3 -1.091641 -0.883538  0.883421  1.269706  0.822185
4  0.911469 -0.883538 -1.198184  1.269706 -0.641495
5  0.911469  1.269089 -1.255854  1.486603 -0.641495
6  1.113200  0.685717 -1.255854       NaN -0.641495
7  1.113200 -0.115718 -0.172060       NaN -1.283813
8  0.242572 -0.726256  0.219863       NaN -1.283813
9       NaN       NaN  0.219863       NaN       NaN

In [22]:

print(df)
print(df.mean())

      col_0     col_1     col_2     col_3     col_4
0       NaN -0.488876 -0.909393       NaN  0.108884
1  0.241300  0.464170       NaN -0.033699 -1.513093
2 -0.518444  0.097376  0.654823       NaN  0.084360
3 -1.091641       NaN  0.883421       NaN  0.822185
4       NaN -0.883538 -1.198184  1.269706       NaN
5  0.911469  1.269089       NaN  1.486603       NaN
6       NaN  0.685717 -1.255854       NaN -0.641495
7  1.113200 -0.115718 -0.172060       NaN       NaN
8  0.242572 -0.726256       NaN       NaN -1.283813
9       NaN       NaN  0.219863       NaN       NaN
col_0    0.149743
col_1    0.037745
col_2   -0.253912
col_3    0.907537
col_4   -0.403829
dtype: float64

In [24]:
df.fillna(df.mean())

      col_0     col_1     col_2     col_3     col_4
0  0.149743 -0.488876 -0.909393  0.907537  0.108884
1  0.241300  0.464170 -0.253912 -0.033699 -1.513093
2 -0.518444  0.097376  0.654823  0.907537  0.084360
3 -1.091641  0.037745  0.883421  0.907537  0.822185
4  0.149743 -0.883538 -1.198184  1.269706 -0.403829
5  0.911469  1.269089 -0.253912  1.486603 -0.403829
6  0.149743  0.685717 -1.255854  0.907537 -0.641495
7  1.113200 -0.115718 -0.172060  0.907537 -0.403829
8  0.242572 -0.726256 -0.253912  0.907537 -1.283813
9  0.149743  0.037745  0.219863  0.907537 -0.403829

In [29]:
print(df.shape)
drop_na_rows = df.dropna(axis=0)
print(drop_na_rows)
print(drop_na_rows.shape)

(10, 5)
      col_0     col_1     col_2     col_3     col_4
2  2.735269 -0.462304 -0.450791 -0.320104 -0.759665
3 -0.221267 -0.941401 -0.888113 -0.098734  0.510390
9  0.234275  0.957033  0.018040 -0.355998 -0.146622
(3, 5)

In [30]:
print(df.shape)
drop_na_cols = df.dropna(axis=1)
print(drop_na_cols)
print(drop_na_cols.shape)

(10, 5)
Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
(10, 0)