In [1]:
import pandas as pd 
import numpy as np

# Replacing Missing Data

## Using replacing on a DataFrame

In [13]:
# Sample data
data = {
    'Column1': ['10', 'NA', 'N/A', '-', None, ' ', '25'],
    'Column2': ['100', '200', 'n/a', 'None', 'null', '-', '300'],
    'Column3': ['50', 'n/a', '-', None, 'N/A', 'null', '75'],
    'Column4': ['-', 'None', 'null', '50', '100', 'n/a', None],
    'Column5': ['25', '50', '100', 'n/a', '-', 'None', '150']
}


df = pd.DataFrame(data)

# Replacing missing value indicators with NaN
df.replace(['NA', 'N/A', 'n/a', 'None', 'null', '-', ' ',None], np.nan, inplace=True)

df

  Column1 Column2 Column3 Column4 Column5
0      10     100      50     NaN      25
1     NaN     200     NaN     NaN      50
2     NaN     NaN     NaN     NaN     100
3     NaN     NaN     NaN      50     NaN
4     NaN     NaN     NaN     100     NaN
5     NaN     NaN     NaN     NaN     NaN
6      25     300      75     NaN     150

##  Using na_values on Read_CSV

In [4]:
df = pd.read_csv('sample_data.csv', na_values=['NA', 'N/A', 'n/a', 'None', 'null', '-', ' ',None])
print(df.shape)
df

(7, 5)

   Column1  Column2  Column3  Column4  Column5
0     10.0    100.0     50.0      NaN       25
1      NaN    200.0      NaN      NaN       50
2      NaN      NaN      NaN      NaN      100
3      NaN      NaN      NaN     50.0       13
4      NaN      NaN      NaN    100.0      160
5      NaN      NaN      NaN      NaN       87
6     25.0    300.0     75.0     25.0      150

# Detecting Missing Values

## Using ISNA() method

In [44]:
df.isna()

   Column1  Column2  Column3  Column4  Column5
0    False    False    False     True    False
1     True    False     True     True    False
2     True     True     True     True    False
3     True     True     True    False    False
4     True     True     True    False    False
5     True     True     True     True    False
6    False    False    False    False    False

## Using NOTNA() method

In [45]:
df.notna()

   Column1  Column2  Column3  Column4  Column5
0     True     True     True    False     True
1    False     True    False    False     True
2    False    False    False    False     True
3    False    False    False     True     True
4    False    False    False     True     True
5    False    False    False    False     True
6     True     True     True     True     True

# How Missing Data Behaves in different DataTypes

## Missing Data in Numeric Series or DataFrame(column)

In [20]:
# Assigning a None or np.nan to numeric Series or Dataframe(column) defaults to NaN

df_num = pd.Series([11.0, np.nan, 5, 9, 7,2.8 ,None])

df_num

0    11.0
1     NaN
2     5.0
3     9.0
4     7.0
5     2.8
6     NaN
dtype: float64

## Missing Data in DateTime Series or DataFrame(column)

In [22]:
# Assigning a None or np.nan to datetime Series or Dataframe(column) defaults to NaT

df_dt = pd.Series(['2024-01-01', None, '2024-12-26', np.nan,'2025-01-03'])

df_dt = pd.to_datetime(df_dt)

df_dt

0   2024-01-01
1          NaT
2   2024-12-26
3          NaT
4   2025-01-03
dtype: datetime64[ns]

## Missing Data in Object Series or DataFrame(column)

In [31]:
# None and np.nan are treated as generic missing values in an Object Series or DataFrame(column).

df_obj = pd.Series([57,'sadat', None, 'z',pd.to_datetime('2025-01-03'), np.nan,20.89])

df_obj

0                     57
1                  sadat
2                   None
3                      z
4    2025-01-03 00:00:00
5                    NaN
6                  20.89
dtype: object

# Filling Missing Data

## Filling with a Scalar Value using fillna

In [46]:
df.fillna(0)
# df.fillna('NA')

   Column1  Column2  Column3  Column4  Column5
0     10.0    100.0     50.0      0.0       25
1      0.0    200.0      0.0      0.0       50
2      0.0      0.0      0.0      0.0      100
3      0.0      0.0      0.0     50.0       13
4      0.0      0.0      0.0    100.0      160
5      0.0      0.0      0.0      0.0       87
6     25.0    300.0     75.0     25.0      150

## Filling with a Series using fillna

In [7]:
# print(df.mean())
# print(type(df.mean()))
# print('---------------------------')
df.fillna(df.mean())

   Column1  Column2  Column3     Column4  Column5
0     10.0    100.0     50.0   58.333333       25
1     17.5    200.0     62.5   58.333333       50
2     17.5    200.0     62.5   58.333333      100
3     17.5    200.0     62.5   50.000000       13
4     17.5    200.0     62.5  100.000000      160
5     17.5    200.0     62.5   58.333333       87
6     25.0    300.0     75.0   25.000000      150

## Filling cells using Forward Fill (ffill)

In [48]:
df.ffill()
# df.fillna(method='ffill') is another way of achieving the same results

   Column1  Column2  Column3  Column4  Column5
0     10.0    100.0     50.0      NaN       25
1     10.0    200.0     50.0      NaN       50
2     10.0    200.0     50.0      NaN      100
3     10.0    200.0     50.0     50.0       13
4     10.0    200.0     50.0    100.0      160
5     10.0    200.0     50.0    100.0       87
6     25.0    300.0     75.0     25.0      150

## Filling cells using Backward Fill (bfill)

In [49]:
df.bfill()

   Column1  Column2  Column3  Column4  Column5
0     10.0    100.0     50.0     50.0       25
1     25.0    200.0     75.0     50.0       50
2     25.0    300.0     75.0     50.0      100
3     25.0    300.0     75.0     50.0       13
4     25.0    300.0     75.0    100.0      160
5     25.0    300.0     75.0     25.0       87
6     25.0    300.0     75.0     25.0      150

# Dropping Missing Data

## Drop rows with missing values

In [50]:
# Drop rows with missing values
df.dropna(axis=0)

   Column1  Column2  Column3  Column4  Column5
6     25.0    300.0     75.0     25.0      150

## Drop columns with missing values

In [51]:
# Drop columns with missing values
df.dropna(axis=1)

   Column5
0       25
1       50
2      100
3       13
4      160
5       87
6      150