In [6]:
import pandas as pd 
import  numpy as np

In [8]:
rows, cols = 5,3

data = np.random.randn(rows,cols)


df= pd.DataFrame(data,columns=[f'col_{i}' for i in range(cols)],index=[1, 2, 3, 5, 8])

df

# colors = pd.Series(
#     ["red", "purple", "blue", "green", "yellow"],
#    index=[1, 2, 3, 5, 8]
# )
# colors

      col_0     col_1     col_2
1  0.467965  0.823086 -1.583423
2 -0.236728  0.930543 -0.393730
3  0.613946  0.839053  1.655876
5 -1.054890 -0.586198  1.155198
8  0.659610  2.465685 -0.261807

In [22]:
df.col_0

1    0.467965
2   -0.236728
3    0.613946
5   -1.054890
8    0.659610
Name: col_0, dtype: float64

In [15]:
df[['col_0','col_2']]

      col_0     col_2
1  0.467965 -1.583423
2 -0.236728 -0.393730
3  0.613946  1.655876
5 -1.054890  1.155198
8  0.659610 -0.261807

In [19]:
df[:1]

      col_0     col_1     col_2
1  0.467965  0.823086 -1.583423

In [23]:
df[0:3]

      col_0     col_1     col_2
1  0.467965  0.823086 -1.583423
2 -0.236728  0.930543 -0.393730
3  0.613946  0.839053  1.655876

In [25]:
df

      col_0     col_1     col_2
1  0.467965  0.823086 -1.583423
2 -0.236728  0.930543 -0.393730
3  0.613946  0.839053  1.655876
5 -1.054890 -0.586198  1.155198
8  0.659610  2.465685 -0.261807

In [36]:
df.loc[3:]

      col_0     col_1     col_2
3  0.613946  0.839053  1.655876
5 -1.054890 -0.586198  1.155198
8  0.659610  2.465685 -0.261807

In [38]:
df.loc[3]

col_0    0.613946
col_1    0.839053
col_2    1.655876
Name: 3, dtype: float64

In [39]:
df.loc['col_0']

KeyError: 'col_0'